db_host: '{{ vault_db_host }}'
db_name: '{{ vault_db_name }}'
db_port: '{{ vault_db_port }}'
db_username: '{{ vault_db_username }}'
db_pass: '{{ vault_db_pass }}'

datadog_api_key: '{{ vault_datadog_api_key }}'
